// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {deck} from '../models';

export function GetAllDecks():Promise<Array<main.DeckSummary>>;

export function GetDeck(arg1:string):Promise<deck.Deck>;

export function ReloadDecks():Promise<Array<main.DeckSummary>>;
