// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCards(arg1, arg2) {
  return window['go']['main']['App']['AddCards'](arg1, arg2);
}

export function GetAllDecks() {
  return window['go']['main']['App']['GetAllDecks']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetDeck(arg1) {
  return window['go']['main']['App']['GetDeck'](arg1);
}

export function GetDeckBasic(arg1) {
  return window['go']['main']['App']['GetDeckBasic'](arg1);
}

export function InitializeAndSelectFolder() {
  return window['go']['main']['App']['InitializeAndSelectFolder']();
}

export function ReloadDecks() {
  return window['go']['main']['App']['ReloadDecks']();
}

export function RemoveCard(arg1, arg2) {
  return window['go']['main']['App']['RemoveCard'](arg1, arg2);
}

export function RemoveKnownCollection(arg1) {
  return window['go']['main']['App']['RemoveKnownCollection'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function SelectCollectionFolder() {
  return window['go']['main']['App']['SelectCollectionFolder']();
}

export function SwitchCollection(arg1) {
  return window['go']['main']['App']['SwitchCollection'](arg1);
}

export function ToggleCardTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleCardTag'](arg1, arg2, arg3);
}

export function UpdateCardQuantity(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCardQuantity'](arg1, arg2, arg3);
}

export function UpdateDeckInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDeckInfo'](arg1, arg2, arg3);
}
