// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDecks() {
  return window['go']['main']['App']['GetAllDecks']();
}

export function GetDeck(arg1) {
  return window['go']['main']['App']['GetDeck'](arg1);
}

export function ReloadDecks() {
  return window['go']['main']['App']['ReloadDecks']();
}
